### ISSUE TITLE
请问如何跨平台编译

### ISSUE THREAD

**Issue by liushooter** [kekeimiku/msrs#2]
请问如何在mac 平台编译 这个项目呢 https://github.com/kekeimiku/msrs/tree/main/%E8%AE%A9%E5%B1%8F%E5%B9%95%E9%80%90%E6%B8%90%E8%9E%8D%E5%8C%96

**Comment by kekeimiku** [comment]
```
rustup target add x86_64-pc-windows-gnu
cargo build --release --target x86_64-pc-windows-gnu
```
试试这样？我在linux上面这样可以编译，不过相比msvc会大一些。

**Comment by poly000** [comment]
另外可以试试wine msvc
